---
title: "BB503/BB602 - Probability & Statististics - Fall 2021"
output: github_document
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r schedule, echo=FALSE}
suppressMessages(sched_df <- readxl::read_excel("misc/grad_lectures.xlsx"))

sched_df$Slides <- sched_df$`R script` <- NULL
colnames(sched_df)[4] <- "HW"
sched_df$HW[is.na(sched_df$HW)] <- ""

# function for creating link
link_to_file <- function(text, rel_path) {
    URL <- paste0("https://github.com/egeulgen/BB503_BB602_21_22/blob/main/", rel_path)
    new_text <- kableExtra::cell_spec(text, "html", link = URL)
    return(new_text)
}

# links to HWs
sched_df$HW[3] <- link_to_file(sched_df$HW[3], "Homeworks/HW1.pdf")
sched_df$HW[9] <- link_to_file(sched_df$HW[9], "Homeworks/HW2.pdf")


# links to lectures
sched_df$Subject[1] <- link_to_file(sched_df$Subject[1], "lectures/1.descriptive.pdf")
sched_df$Subject[2] <- link_to_file(sched_df$Subject[2], "lectures/2.descriptive.pdf")
sched_df$Subject[3] <- link_to_file(sched_df$Subject[3], "lectures/3.probability.pdf")
sched_df$Subject[4] <- link_to_file(sched_df$Subject[4], "lectures/4.discrete_distributions.pdf")
sched_df$Subject[5] <- link_to_file(sched_df$Subject[5], "lectures/5.continuous_distributions.pdf")
sched_df$Subject[7] <- link_to_file(sched_df$Subject[7], "lectures/7.MLE_LLN_CLT_hypothesis.pdf")
sched_df$Subject[8] <- link_to_file(sched_df$Subject[8], "lectures/8.ANOVA_chi_squared.pdf")
sched_df$Subject[9] <- link_to_file(sched_df$Subject[9], "lectures/9.nonparametric_multiple_testing.pdf")
sched_df$Subject[11] <- link_to_file(sched_df$Subject[11], "lectures/11.Missing_power_linear_regression.pdf")


# links to R exercises
sched_df$R <- ""
sched_df$R[1] <- link_to_file("Intro", "scripts/1.intro.R")
sched_df$R[2] <- link_to_file("EDA", "scripts/2.EDA.pdf")
sched_df$R[3] <- link_to_file("Basics", "scripts/3.basics.pdf")
sched_df$R[4] <- link_to_file("Discrete RV", "scripts/4.discrete_distr.pdf")
sched_df$R[5] <- link_to_file("Cont. RV", "scripts/5.cont_distr.pdf")
sched_df$R[7] <- link_to_file("Hyp.Test", "scripts/7.hypothesis_tests_1.pdf")
sched_df$R[8] <- link_to_file("Hyp.Test", "scripts/8.hypothesis_tests_2.pdf")
sched_df$R[9] <- link_to_file("Hyp.Test", "scripts/9.hypothesis_tests_3.pdf")
sched_df$R[11] <- link_to_file("Lin.Regr.", "scripts/11.linear_regression.pdf")

sched_df <- sched_df[, c(1:3, 5, 4)]

kableExtra::row_spec(kableExtra::row_spec(knitr::kable(sched_df, format = "html", escape = FALSE), which(grepl("Midterm", sched_df$Subject)), bold = TRUE, background = "#F4B41A"), nrow(sched_df), bold = TRUE, background = "#E2725A")

```